In [1]:
import numpy as np

In [2]:
v1 = np.array([10, 6, 6]) #Line
v2 = np.array([3, 5, 12])
v3 = np.array(3)   #scalar

print(v1.ndim)
print(v3.ndim)
print(v1.shape)

1
0
(3,)


In [3]:
class Student :
    def __init__(self, name, age):

        self._name = name      #Protected
        self.age = age

    @property
    def name(self):
        return f'{self._name}'          #read only function

        

In [4]:
s1 = Student('Amr', 21)
s1.name

'Amr'

In [5]:
vec = np.array([1, 2, 3, 4, 5, 6])
mat = vec.reshape((2, 3))
print(vec)
print(mat)
print(vec.shape[0])

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
6


In [6]:
vec1 = np.array([1, 2, 3, 4])
mat1 = vec1.reshape((vec1.shape[0], 1))
print(mat1)

[[1]
 [2]
 [3]
 [4]]


In [7]:
vec1 = np.array([1, 2, 3, 4])
mat1 = vec1[:,None]
print(mat1)

[[1]
 [2]
 [3]
 [4]]


In [8]:
vec1 = np.array([1, 2, 3, 4])
mat1 = vec1.reshape((4,1))
print(mat1)

[[1]
 [2]
 [3]
 [4]]


In [9]:
def array_reshape(arr, rows = -1, cols = -1) :
    try :
        arr = np.array(arr)
        return arr.reshape((rows, cols))
    
    except Exception as e:
        raise ValueError('Invalid reshape operations : {e}')

In [10]:
vec = [1, 4, 2, 4, 11, 22]
print('test 1(2 * 3)matrix' , array_reshape(vec, 2 ,3))

test 1(2 * 3)matrix [[ 1  4  2]
 [ 4 11 22]]


Object m , string, float, int, bool, complex

In [11]:
class C :
    x = 'o'

o1 = C()

In [12]:
mat = np.array([[1,2,o1],
                [4,5,6]])
mat.dtype

dtype('O')

In [13]:
mat = np.array([[1,2,True],
                [4,5,6]])
fmat= mat.astype(float)
print(fmat)
print(fmat.dtype)

[[1. 2. 1.]
 [4. 5. 6.]]
float64


In [14]:
mat = np.array([[1,2,True],
                [4,5,6]])
fmat= mat.astype(str)
print(fmat)
print(fmat.dtype)

[['1' '2' '1']
 ['4' '5' '6']]
<U21


In [15]:
v = np.array([3,2,5,1])
print(v[2])
print(v[1:30])

5
[2 5 1]


In [16]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [0, 0, 0]])
m[1,2]
print(m[1:3 , 0:2])

[[4 5]
 [7 8]]


In [17]:
mat = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

mar_transpose = mat.T
print(mar_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [18]:
mat = np.zeros((3,3))
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
mat = np.ones((3,3))
mat

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
mean_filter = np.full((3,3), 10)
mean_filter

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [21]:
mean_filter = np.empty((3,3))
mean_filter

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
angles = np.arange(0, 360, 90)
angles

array([  0,  90, 180, 270])

In [23]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [24]:
vec = np.linspace(0, 10, num = 25)
mat = vec.reshape((5, 5))
mat

array([[ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667],
       [ 2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ],
       [ 4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333],
       [ 6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667],
       [ 8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ]])

In [25]:
i = np.identity(3, dtype = 'int64')
i

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
np.random.random((3, 3))

array([[0.52631584, 0.3621443 , 0.96555253],
       [0.96827846, 0.44866497, 0.20660291],
       [0.62027805, 0.46348954, 0.45976748]])

In [27]:
np.random.randint(0,11,(5,5))

array([[ 6,  3,  8,  2,  2],
       [ 8,  5,  3,  5, 10],
       [ 6,  5,  0,  9,  5],
       [ 5,  3,  1,  5,  9],
       [10,  1,  0,  5,  3]], dtype=int32)

In [28]:
a = ['Amr', 'Faris', 'Fahd', 'Mahmoud']
np.random.choice(a, size = (3,4))

array([['Amr', 'Faris', 'Faris', 'Fahd'],
       ['Amr', 'Faris', 'Amr', 'Mahmoud'],
       ['Mahmoud', 'Amr', 'Mahmoud', 'Fahd']], dtype='<U7')

In [29]:
mat1 = np.ones((3,4))
mat2 = np.zeros((3,5))

np.savez('file_test.npz',ones_mat = mat1, zeros_mat =mat2)


In [30]:
with np.load('file_test.npz') as file :
    mat1 =file['ones_mat']
    mat2 =file['zeros_mat']

In [31]:
print(mat1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
m1 = np.array([[1, 2, 3],
               [0, 0, 0]])

m2 = np.array([[5, 6, 7],
               [1, 1, 1]])

mat3 = np.vstack((m1 ,m2))
mat3



array([[1, 2, 3],
       [0, 0, 0],
       [5, 6, 7],
       [1, 1, 1]])

In [33]:
m1 = np.array([[1, 2, 3],
               [0, 0, 0]])

m2 = np.array([[5, 6, 7],
               [1, 1, 1]])

mat3 = np.hstack((m1 ,m2))
mat3



array([[1, 2, 3, 5, 6, 7],
       [0, 0, 0, 1, 1, 1]])

In [34]:
s = 4 
v = np.array([4,2,3,4,2,10])
# v == s
v.__eq__(s)

array([ True, False, False,  True, False, False])

In [37]:
v = np.array([2, 4, 3, 4, 10])
condition =  v >= 4
# v[condition] = -1
new_arr = np.where(condition, -1, v)
# print(v)
# print(condition)
print(new_arr)

[ 2 -1  3 -1 -1]


In [38]:
v1 = np.array([1, 2, 3])
c = 2
summation = v1 + c
multip = v1 * c

print(summation)
print(multip)

[3 4 5]
[2 4 6]


In [41]:
mat1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

v2 = np.array([0.5, 0.5, 0.1])

matrix3 = mat1 + v2
matrix4 = mat1 * v2

print(matrix3)
print('*' * 50)
print(matrix4)

[[1.5 2.5 3.1]
 [4.5 5.5 6.1]
 [7.5 8.5 9.1]]
**************************************************
[[0.5 1.  0.3]
 [2.  2.5 0.6]
 [3.5 4.  0.9]]
